version: 2.1 # Use 2.1 to enable using orbs and other features.

# Declare the orbs that we'll use in our config.
# read more about orbs: https://circleci.com/docs/2.0/orb-intro/
orbs:
  macos: circleci/macos@2

jobs:
  build:
    macos:
      xcode: 13.4.0
    steps:
      - checkout
      - run:
          command: gem install bundler:2.3.8
      - macos/switch-ruby:
          version: "2.7.4"
      - run:
          command: bundle install
      - run:
          command: rails db:create
      - run:
          command: rails db:migrate
      - run:
          command: bundle exec rspec


# We use workflows to orchestrate the jobs that we declared above.
workflows:
  version: 2
  build_and_test:     # The name of our workflow is "build_and_test"
    jobs:             # The list of jobs we run as part of this workflow.
      - build
