version: 2.1 # Use 2.1 to enable using orbs and other features.

# Declare the orbs that we'll use in our config.
# read more about orbs: https://circleci.com/docs/2.0/orb-intro/

jobs:
  build: # our first job, named "build"
    docker:
      - image: cimg/ruby:2.7.4-node # use a tailored CircleCI docker image.
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          command: curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
      - run:
          command: bundle install
      - run:
          command: bundle exec rspec 


# We use workflows to orchestrate the jobs that we declared above.
workflows:
  version: 2
  build_and_test:     # The name of our workflow is "build_and_test"
    jobs:             # The list of jobs we run as part of this workflow.
      - build
